---
galaxy_info:
  author: jian
  description: an ansible role for installing apache spark
  min_ansible_version: 1.8
  platforms:
    -name: Centos
    versions:
      - 7.2-64-nocm
  categories:
    - system
  dependencies:
    - { role: "java",  when: java_8_installed }  